### ISSUE TITLE
Typesense Official Guide not working for Python

### ISSUE THREAD

**Issue by radioactive11** [typesense/typesense-python#30] opened 2023-03-03 15:17 UTC
## Description

The Typesense official guide on building a search application is not inserting any documents in the database. No error is being raised and thus searches are returning no values.

## Steps to reproduce

- Installed Typesense0.24 using Homebrew
- Using Jupyter Notebook
- [View the notebook](https://github.com/radioactive11/typesense-sample/blob/master/Typesense%20Search.ipynb)

## Expected Behavior

Getting search results

## Actual Behavior

No search results returned

## Metadata

**Typesense Version**: 0.24.0

**OS**: macOS Version 13.2.1 (22D68)

**Comment by radioactive11** [comment] 2023-03-04 16:38
I debugged the issue and it seems like sending a list of dicts to the import_ function is working fine. 
Can someone check if this is the desired behaviour? If yes then I can raise a PR to correct the docs.

cc: @kishorenc

**Comment by kishorenc** [comment] 2023-03-05 10:17
Thank you for reporting this issue @radioactive11 

Sorry, there was a regression when support was added for generators. This is fixed in `v0.15.1` that I just published. Please try that out and let me know if the problem is fixed. Documents can be sent as both list of dicts and as well as a JSONL string.

**Closed** 2023-06-09 08:45 UTC
